// <auto-generated />
namespace ExamRoom_R33.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dfk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfk));
        
        string IMigrationMetadata.Id
        {
            get { return "201805050828502_dfk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
